import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { ShoppingBag, Bell, LogOut, ArrowRight } from 'lucide-react';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { useMicroMoveStore } from '@/store/microMoveStore';
export const EmployeeLayout = ({ children, onLogout, currentView, onNavigate }) => {
    const user = useMicroMoveStore(state => state.user);
    return (_jsxs("div", { className: "min-h-screen bg-slate-50 font-sans", children: [_jsxs("header", { className: "h-20 bg-white/80 backdrop-blur-xl border-b border-slate-200/60 flex items-center justify-between px-6 md:px-10 sticky top-0 z-20", children: [_jsx("div", { className: "flex items-center gap-4", children: currentView === 'store' ? (_jsxs("button", { onClick: () => onNavigate('home'), className: "flex items-center gap-2 text-sm font-bold text-slate-600 hover:text-slate-900 transition-colors", children: [_jsx(ArrowRight, { className: "w-5 h-5" }), _jsx("span", { children: "\u0627\u0644\u0631\u062C\u0648\u0639" })] })) : (_jsx("img", { src: "/logo.png", alt: "Micro Move", className: "h-8" })) }), _jsxs("div", { className: "flex items-center gap-3 md:gap-4", children: [currentView !== 'store' && (_jsxs(Button, { onClick: () => onNavigate('store'), variant: "outline", className: "border-slate-200 shadow-sm rounded-xl font-bold hover:bg-slate-50 h-10 px-4 group", children: [_jsx(ShoppingBag, { className: "w-4 h-4 ml-2 text-primary group-hover:scale-110 transition-transform" }), "\u0627\u0644\u0645\u062A\u062C\u0631"] })), _jsxs("div", { className: "hidden sm:flex items-center gap-1 px-3 py-1.5 bg-orange-50 border border-orange-200/60 rounded-xl text-sm font-bold text-orange-600", children: [user?.points.toLocaleString(), " \u0646\u0642\u0637\u0629"] }), _jsxs(Button, { variant: "ghost", size: "icon", className: "relative text-slate-500 hover:bg-slate-100 rounded-full w-10 h-10 transition-colors", children: [_jsx(Bell, { className: "w-5 h-5" }), _jsx("span", { className: "absolute top-2.5 left-2.5 w-2 h-2 bg-primary rounded-full ring-2 ring-white" })] }), _jsxs(Avatar, { className: "w-10 h-10 border border-slate-200 shadow-sm", children: [_jsx(AvatarImage, { src: `https://i.pravatar.cc/150?u=${user?.email}` }), _jsx(AvatarFallback, { className: "bg-primary/10 text-primary font-bold", children: user?.name[0] })] }), _jsx("button", { onClick: onLogout, className: "text-slate-400 hover:text-red-500 transition-colors p-2 rounded-full hover:bg-red-50", title: "\u062A\u0633\u062C\u064A\u0644 \u0627\u0644\u062E\u0631\u0648\u062C", children: _jsx(LogOut, { className: "w-5 h-5" }) })] })] }), _jsx("main", { className: "relative", children: _jsx("div", { className: "max-w-7xl mx-auto px-4 md:px-10 py-8", children: children }) })] }));
};
